publish:
  image: node:14
  stage: deploy
  only:
    - master
  script:
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - |
      if [[ $(npm view "${NPM_PACKAGE_NAME}" versions) =~ "'${NPM_PACKAGE_VERSION}'" ]]; then
        echo "Version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} has already been published, so no new version has been published."
        exit 1
      fi
    - npm install npm@latest -g
    - npm ci
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
    - npm publish --access=public
    - echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME}."

test-publishing:
  image: node:14
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
  script:
    - npm install npm@latest -g
    - npm ci
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
    - npm publish --access=public --dry-run
    - echo "Publishing is possible"
